#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openjdk12
Version  : 12.0.1
Release  : 1
URL      : http://hg.openjdk.java.net/jdk-updates/jdk12u/archive/jdk-12.0.1-ga.zip
Source0  : http://hg.openjdk.java.net/jdk-updates/jdk12u/archive/jdk-12.0.1-ga.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 Libpng MIT
Requires: openjdk12-bin = %{version}-%{release}
Requires: openjdk12-lib = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : ca-certs
BuildRequires : ccache
BuildRequires : cups-dev
BuildRequires : fontconfig-dev
BuildRequires : freetype-dev
BuildRequires : glibc-bin
BuildRequires : graphviz
BuildRequires : libX11-dev
BuildRequires : libXext-dev
BuildRequires : libXi-dev
BuildRequires : libXrender-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : openjdk11
BuildRequires : openjdk11-dev
BuildRequires : zip

%description
Welcome to the JDK!
===================
For information about building the JDK, including how to retrieve all
of the source code, please see either of these files:

%package bin
Summary: bin components for the openjdk12 package.
Group: Binaries

%description bin
bin components for the openjdk12 package.


%package dev
Summary: dev components for the openjdk12 package.
Group: Development
Requires: openjdk12-lib = %{version}-%{release}
Requires: openjdk12-bin = %{version}-%{release}
Provides: openjdk12-devel = %{version}-%{release}
Requires: openjdk12 = %{version}-%{release}

%description dev
dev components for the openjdk12 package.


%package lib
Summary: lib components for the openjdk12 package.
Group: Libraries

%description lib
lib components for the openjdk12 package.


%prep
%setup -q -n jdk12u-jdk-12.0.1-ga

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1563440564
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
## make_prepend content
export CC=/usr/bin/gcc
export CXX=/usr/bin/g++
bash configure \
--with-boot-jdk=/usr/lib/jvm/java-1.11.0-openjdk \
--x-includes=/usr/include/ \
--x-libraries=/usr/lib64 \
--with-zlib=system \
--enable-ccache \
--disable-warnings-as-errors \
--prefix=%{buildroot}/usr/lib
## make_prepend end
make  %{?_smp_mflags} || make images WARNINGS_ARE_ERRORS="-Wno-error" CFLAGS_WARNINGS_ARE_ERRORS="-Wno-error" VERSION_STRING="12.0.1-ga" VERSION_SHORT="12.0.1"


%install
export SOURCE_DATE_EPOCH=1563440564
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openjdk12
cp LICENSE %{buildroot}/usr/share/package-licenses/openjdk12/LICENSE
cp src/java.desktop/share/native/libsplashscreen/giflib/COPYING %{buildroot}/usr/share/package-licenses/openjdk12/src_java.desktop_share_native_libsplashscreen_giflib_COPYING
cp src/java.desktop/share/native/libsplashscreen/libpng/LICENSE %{buildroot}/usr/share/package-licenses/openjdk12/src_java.desktop_share_native_libsplashscreen_libpng_LICENSE
cp src/java.smartcardio/unix/native/libj2pcsc/MUSCLE/COPYING %{buildroot}/usr/share/package-licenses/openjdk12/src_java.smartcardio_unix_native_libj2pcsc_MUSCLE_COPYING
cp test/fmw/gtest/LICENSE %{buildroot}/usr/share/package-licenses/openjdk12/test_fmw_gtest_LICENSE
%make_install
## install_append content
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/lib/jvm/java-1.12.0-openjdk
cp -r build/linux-x86_64-server-release/images/jdk/* %{buildroot}/usr/lib/jvm/java-1.12.0-openjdk
mkdir -p %{buildroot}/usr/lib64
ln -s /usr/lib/jvm/java-1.12.0-openjdk/lib/jli/libjli.so %{buildroot}/usr/lib64/libjli12.so
mkdir -p %{buildroot}/usr/bin
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jaotc %{buildroot}/usr/bin/jaotc12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jar %{buildroot}/usr/bin/jar12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jarsigner %{buildroot}/usr/bin/jarsigner12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/java %{buildroot}/usr/bin/java12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/javac %{buildroot}/usr/bin/javac12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/javadoc %{buildroot}/usr/bin/javadoc12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/javap %{buildroot}/usr/bin/javap12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jcmd %{buildroot}/usr/bin/jcmd12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jconsole %{buildroot}/usr/bin/jconsole12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jdb %{buildroot}/usr/bin/jdb12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jdeprscan %{buildroot}/usr/bin/jdeprscan12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jfr %{buildroot}/usr/bin/jfr12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jdeps %{buildroot}/usr/bin/jdeps12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jhsdb %{buildroot}/usr/bin/jhsdb12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jimage %{buildroot}/usr/bin/jimage12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jinfo %{buildroot}/usr/bin/jinfo12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jjs %{buildroot}/usr/bin/jjs12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jlink %{buildroot}/usr/bin/jlink12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jmap %{buildroot}/usr/bin/jmap12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jmod %{buildroot}/usr/bin/jmod12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jps %{buildroot}/usr/bin/jps12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jrunscript %{buildroot}/usr/bin/jrunscript12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jshell %{buildroot}/usr/bin/jshell12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jstack %{buildroot}/usr/bin/jstack12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jstat %{buildroot}/usr/bin/jstat12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/jstatd %{buildroot}/usr/bin/jstatd12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/keytool  %{buildroot}/usr/bin/keytool12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/pack200  %{buildroot}/usr/bin/pack20012
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/rmic  %{buildroot}/usr/bin/rmic12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/rmid  %{buildroot}/usr/bin/rmid12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/rmiregistry %{buildroot}/usr/bin/rmiregistry12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/serialver %{buildroot}/usr/bin/serialver12
ln -s /usr/lib/jvm/java-1.12.0-openjdk/bin/unpack200 %{buildroot}/usr/bin/unpack20012
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/jvm/java-1.12.0-openjdk/bin/jaotc
/usr/lib/jvm/java-1.12.0-openjdk/bin/jar
/usr/lib/jvm/java-1.12.0-openjdk/bin/jarsigner
/usr/lib/jvm/java-1.12.0-openjdk/bin/java
/usr/lib/jvm/java-1.12.0-openjdk/bin/javac
/usr/lib/jvm/java-1.12.0-openjdk/bin/javadoc
/usr/lib/jvm/java-1.12.0-openjdk/bin/javap
/usr/lib/jvm/java-1.12.0-openjdk/bin/jcmd
/usr/lib/jvm/java-1.12.0-openjdk/bin/jconsole
/usr/lib/jvm/java-1.12.0-openjdk/bin/jdb
/usr/lib/jvm/java-1.12.0-openjdk/bin/jdeprscan
/usr/lib/jvm/java-1.12.0-openjdk/bin/jdeps
/usr/lib/jvm/java-1.12.0-openjdk/bin/jfr
/usr/lib/jvm/java-1.12.0-openjdk/bin/jhsdb
/usr/lib/jvm/java-1.12.0-openjdk/bin/jimage
/usr/lib/jvm/java-1.12.0-openjdk/bin/jinfo
/usr/lib/jvm/java-1.12.0-openjdk/bin/jjs
/usr/lib/jvm/java-1.12.0-openjdk/bin/jlink
/usr/lib/jvm/java-1.12.0-openjdk/bin/jmap
/usr/lib/jvm/java-1.12.0-openjdk/bin/jmod
/usr/lib/jvm/java-1.12.0-openjdk/bin/jps
/usr/lib/jvm/java-1.12.0-openjdk/bin/jrunscript
/usr/lib/jvm/java-1.12.0-openjdk/bin/jshell
/usr/lib/jvm/java-1.12.0-openjdk/bin/jstack
/usr/lib/jvm/java-1.12.0-openjdk/bin/jstat
/usr/lib/jvm/java-1.12.0-openjdk/bin/jstatd
/usr/lib/jvm/java-1.12.0-openjdk/bin/keytool
/usr/lib/jvm/java-1.12.0-openjdk/bin/pack200
/usr/lib/jvm/java-1.12.0-openjdk/bin/rmic
/usr/lib/jvm/java-1.12.0-openjdk/bin/rmid
/usr/lib/jvm/java-1.12.0-openjdk/bin/rmiregistry
/usr/lib/jvm/java-1.12.0-openjdk/bin/serialver
/usr/lib/jvm/java-1.12.0-openjdk/bin/unpack200
/usr/lib/jvm/java-1.12.0-openjdk/conf/logging.properties
/usr/lib/jvm/java-1.12.0-openjdk/conf/management/jmxremote.access
/usr/lib/jvm/java-1.12.0-openjdk/conf/management/jmxremote.password.template
/usr/lib/jvm/java-1.12.0-openjdk/conf/management/management.properties
/usr/lib/jvm/java-1.12.0-openjdk/conf/net.properties
/usr/lib/jvm/java-1.12.0-openjdk/conf/sdp/sdp.conf.template
/usr/lib/jvm/java-1.12.0-openjdk/conf/security/java.policy
/usr/lib/jvm/java-1.12.0-openjdk/conf/security/java.security
/usr/lib/jvm/java-1.12.0-openjdk/conf/security/policy/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/conf/security/policy/limited/default_US_export.policy
/usr/lib/jvm/java-1.12.0-openjdk/conf/security/policy/limited/default_local.policy
/usr/lib/jvm/java-1.12.0-openjdk/conf/security/policy/limited/exempt_local.policy
/usr/lib/jvm/java-1.12.0-openjdk/conf/security/policy/unlimited/default_US_export.policy
/usr/lib/jvm/java-1.12.0-openjdk/conf/security/policy/unlimited/default_local.policy
/usr/lib/jvm/java-1.12.0-openjdk/conf/sound.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/README
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/CodePointIM/CodePointIM.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/CodePointIM/README.html
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/CodePointIM/README_ja.html
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/CodePointIM/README_zh_CN.html
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/CodePointIM/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/FileChooserDemo/FileChooserDemo.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/FileChooserDemo/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/FileChooserDemo/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Font2DTest/Font2DTest.html
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Font2DTest/Font2DTest.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Font2DTest/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Font2DTest/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/J2Ddemo/J2Ddemo.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/J2Ddemo/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/J2Ddemo/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Metalworks/Metalworks.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Metalworks/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Metalworks/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Notepad/Notepad.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Notepad/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Notepad/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/SampleTree/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/SampleTree/SampleTree.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/SampleTree/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Stylepad/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Stylepad/Stylepad.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/Stylepad/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/SwingSet2/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/SwingSet2/SwingSet2.html
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/SwingSet2/SwingSet2.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/SwingSet2/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/TableExample/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/TableExample/TableExample.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/TableExample/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/TransparentRuler/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/TransparentRuler/TransparentRuler.jar
/usr/lib/jvm/java-1.12.0-openjdk/demo/jfc/TransparentRuler/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/README.txt
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/FileChooserDemo/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/FileChooserDemo/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/FileChooserDemo/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/FileChooserDemo/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/FileChooserDemo/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/FileChooserDemo/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Font2DTest/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Font2DTest/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Font2DTest/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Font2DTest/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Font2DTest/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Font2DTest/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Metalworks/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Metalworks/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Metalworks/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Metalworks/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Metalworks/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Metalworks/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Notepad/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Notepad/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Notepad/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Notepad/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Notepad/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/Notepad/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SampleTree/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SampleTree/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SampleTree/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SampleTree/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SampleTree/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SampleTree/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SwingApplet/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SwingApplet/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SwingApplet/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SwingApplet/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SwingApplet/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/SwingApplet/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TableExample/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TableExample/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TableExample/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TableExample/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TableExample/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TableExample/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TransparentRuler/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TransparentRuler/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TransparentRuler/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TransparentRuler/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TransparentRuler/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/jfc/TransparentRuler/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/FullThreadDump/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/FullThreadDump/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/FullThreadDump/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/FullThreadDump/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/FullThreadDump/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/FullThreadDump/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/JTop/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/JTop/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/JTop/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/JTop/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/JTop/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/JTop/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/MemoryMonitor/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/MemoryMonitor/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/MemoryMonitor/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/MemoryMonitor/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/MemoryMonitor/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/MemoryMonitor/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/VerboseGC/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/VerboseGC/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/VerboseGC/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/VerboseGC/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/VerboseGC/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/management/VerboseGC/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/scripting/jconsole-plugin/build.properties
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/scripting/jconsole-plugin/build.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/scripting/jconsole-plugin/nbproject/file-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/scripting/jconsole-plugin/nbproject/jdk.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/scripting/jconsole-plugin/nbproject/netbeans-targets.xml
/usr/lib/jvm/java-1.12.0-openjdk/demo/nbproject/scripting/jconsole-plugin/nbproject/project.xml
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.base.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.compiler.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.datatransfer.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.desktop.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.instrument.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.logging.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.management.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.management.rmi.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.naming.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.net.http.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.prefs.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.rmi.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.scripting.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.se.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.security.jgss.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.security.sasl.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.smartcardio.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.sql.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.sql.rowset.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.transaction.xa.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.xml.crypto.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/java.xml.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.accessibility.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.aot.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.attach.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.charsets.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.compiler.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.crypto.cryptoki.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.crypto.ec.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.dynalink.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.editpad.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.hotspot.agent.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.httpserver.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.internal.ed.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.internal.jvmstat.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.internal.le.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.internal.opt.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.internal.vm.ci.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.internal.vm.compiler.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.internal.vm.compiler.management.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jartool.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.javadoc.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jcmd.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jconsole.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jdeps.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jdi.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jdwp.agent.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jfr.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jlink.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jshell.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jsobject.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.jstatd.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.localedata.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.management.agent.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.management.jfr.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.management.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.naming.dns.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.naming.rmi.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.net.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.pack.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.rmic.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.scripting.nashorn.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.scripting.nashorn.shell.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.sctp.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.security.auth.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.security.jgss.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.unsupported.desktop.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.unsupported.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.xml.dom.jmod
/usr/lib/jvm/java-1.12.0-openjdk/jmods/jdk.zipfs.jmod
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/aes.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/asm.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/c-libutl.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/cldr.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/icu.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/public_suffix.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.base/unicode.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.compiler/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.datatransfer/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.datatransfer/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.datatransfer/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/colorimaging.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/giflib.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/harfbuzz.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/jpeg.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/lcms.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/libpng.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/mesa3d.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/opengl.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.desktop/xwd.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.instrument/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.instrument/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.instrument/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.logging/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.logging/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.logging/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.management.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.management.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.management.rmi/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.management/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.naming/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.naming/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.naming/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.net.http/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.net.http/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.net.http/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.prefs/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.prefs/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.prefs/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.rmi/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.scripting/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.scripting/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.scripting/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.se/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.se/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.se/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.security.jgss/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.security.jgss/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.security.jgss/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.security.sasl/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.security.sasl/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.security.sasl/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.smartcardio/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.smartcardio/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.smartcardio/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.smartcardio/pcsclite.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.sql.rowset/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.sql.rowset/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.sql.rowset/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.sql/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.sql/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.sql/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.transaction.xa/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.transaction.xa/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.transaction.xa/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml.crypto/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml.crypto/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml.crypto/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml.crypto/santuario.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml/bcel.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml/dom.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml/jcup.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml/xalan.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/java.xml/xerces.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.accessibility/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.accessibility/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.accessibility/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.aot/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.aot/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.aot/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.attach/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.attach/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.attach/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.charsets/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.charsets/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.charsets/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.compiler/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.cryptoki/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.cryptoki/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.cryptoki/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.cryptoki/pkcs11cryptotoken.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.cryptoki/pkcs11wrapper.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.ec/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.ec/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.ec/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.crypto.ec/ecc.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.dynalink/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.dynalink/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.dynalink/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.dynalink/dynalink.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.editpad/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.editpad/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.editpad/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.hotspot.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.hotspot.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.hotspot.agent/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.httpserver/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.httpserver/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.httpserver/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.ed/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.ed/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.ed/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.jvmstat/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.jvmstat/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.le/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.le/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.le/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.le/jline.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.opt/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.opt/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.opt/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.opt/jopt-simple.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.ci/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.ci/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.ci/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.compiler.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.compiler.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.compiler.management/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.internal.vm.compiler/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jartool/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jartool/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jartool/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.javadoc/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.javadoc/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.javadoc/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.javadoc/jquery-migrate.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.javadoc/jquery.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.javadoc/jqueryUI.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.javadoc/jszip.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.javadoc/pako.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jcmd/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jcmd/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jcmd/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jconsole/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jconsole/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jconsole/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdeps/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdeps/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdeps/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdi/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdwp.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdwp.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jdwp.agent/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jfr/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jfr/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jfr/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jlink/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jlink/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jlink/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jshell/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jshell/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jshell/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jsobject/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jsobject/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jsobject/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jstatd/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jstatd/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.jstatd/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.localedata/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.localedata/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.localedata/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.localedata/cldr.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.localedata/thaidict.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management.agent/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management.jfr/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management.jfr/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management.jfr/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.management/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.naming.dns/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.naming.dns/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.naming.dns/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.naming.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.naming.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.naming.rmi/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.net/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.net/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.net/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.pack/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.pack/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.pack/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.rmic/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.rmic/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.rmic/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.scripting.nashorn.shell/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.scripting.nashorn.shell/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.scripting.nashorn.shell/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.scripting.nashorn/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.scripting.nashorn/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.scripting.nashorn/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.scripting.nashorn/double-conversion.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.scripting.nashorn/joni.md
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.sctp/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.sctp/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.sctp/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.security.auth/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.security.auth/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.security.auth/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.security.jgss/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.security.jgss/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.security.jgss/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.unsupported.desktop/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.unsupported.desktop/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.unsupported.desktop/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.unsupported/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.unsupported/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.unsupported/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.xml.dom/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.xml.dom/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.xml.dom/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.zipfs/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.zipfs/ASSEMBLY_EXCEPTION
/usr/lib/jvm/java-1.12.0-openjdk/legal/jdk.zipfs/LICENSE
/usr/lib/jvm/java-1.12.0-openjdk/lib/classlist
/usr/lib/jvm/java-1.12.0-openjdk/lib/ct.sym
/usr/lib/jvm/java-1.12.0-openjdk/lib/jexec
/usr/lib/jvm/java-1.12.0-openjdk/lib/jexec.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/jfr/default.jfc
/usr/lib/jvm/java-1.12.0-openjdk/lib/jfr/profile.jfc
/usr/lib/jvm/java-1.12.0-openjdk/lib/jrt-fs.jar
/usr/lib/jvm/java-1.12.0-openjdk/lib/jspawnhelper
/usr/lib/jvm/java-1.12.0-openjdk/lib/jspawnhelper.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/jvm.cfg
/usr/lib/jvm/java-1.12.0-openjdk/lib/libattach.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libawt.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libawt_headless.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libawt_xawt.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libdt_socket.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libextnet.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libfontmanager.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libinstrument.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libj2gss.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libj2pcsc.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libj2pkcs11.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjaas.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjava.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjavajpeg.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjawt.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjdwp.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjimage.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjli.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjsig.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjsound.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/liblcms.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libmanagement.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libmanagement_agent.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libmanagement_ext.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libmlib_image.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libnet.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libnio.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libprefs.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/librmi.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libsaproc.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libsctp.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libsplashscreen.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libsunec.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libunpack.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libverify.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/libzip.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/modules
/usr/lib/jvm/java-1.12.0-openjdk/lib/psfont.properties.ja
/usr/lib/jvm/java-1.12.0-openjdk/lib/psfontj2d.properties
/usr/lib/jvm/java-1.12.0-openjdk/lib/security/blacklisted.certs
/usr/lib/jvm/java-1.12.0-openjdk/lib/security/cacerts
/usr/lib/jvm/java-1.12.0-openjdk/lib/security/default.policy
/usr/lib/jvm/java-1.12.0-openjdk/lib/security/public_suffix_list.dat
/usr/lib/jvm/java-1.12.0-openjdk/lib/server/Xusage.txt
/usr/lib/jvm/java-1.12.0-openjdk/lib/server/classes.jsa
/usr/lib/jvm/java-1.12.0-openjdk/lib/server/libjvm.debuginfo
/usr/lib/jvm/java-1.12.0-openjdk/lib/src.zip
/usr/lib/jvm/java-1.12.0-openjdk/lib/tzdb.dat
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jar.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jarsigner.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/java.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/javac.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/javadoc.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/javap.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jcmd.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jconsole.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jdb.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jdeps.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jinfo.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jjs.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jmap.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jps.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jrunscript.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jstack.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jstat.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/jstatd.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/keytool.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/pack200.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/rmic.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/rmid.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/rmiregistry.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/serialver.1
/usr/lib/jvm/java-1.12.0-openjdk/man/man1/unpack200.1
/usr/lib/jvm/java-1.12.0-openjdk/release

%files bin
%defattr(-,root,root,-)
/usr/bin/jaotc12
/usr/bin/jar12
/usr/bin/jarsigner12
/usr/bin/java12
/usr/bin/javac12
/usr/bin/javadoc12
/usr/bin/javap12
/usr/bin/jcmd12
/usr/bin/jconsole12
/usr/bin/jdb12
/usr/bin/jdeprscan12
/usr/bin/jdeps12
/usr/bin/jfr12
/usr/bin/jhsdb12
/usr/bin/jimage12
/usr/bin/jinfo12
/usr/bin/jjs12
/usr/bin/jlink12
/usr/bin/jmap12
/usr/bin/jmod12
/usr/bin/jps12
/usr/bin/jrunscript12
/usr/bin/jshell12
/usr/bin/jstack12
/usr/bin/jstat12
/usr/bin/jstatd12
/usr/bin/keytool12
/usr/bin/pack20012
/usr/bin/rmic12
/usr/bin/rmid12
/usr/bin/rmiregistry12
/usr/bin/serialver12
/usr/bin/unpack20012

%files dev
%defattr(-,root,root,-)
/usr/lib/jvm/java-1.12.0-openjdk/include/classfile_constants.h
/usr/lib/jvm/java-1.12.0-openjdk/include/jawt.h
/usr/lib/jvm/java-1.12.0-openjdk/include/jdwpTransport.h
/usr/lib/jvm/java-1.12.0-openjdk/include/jni.h
/usr/lib/jvm/java-1.12.0-openjdk/include/jvmti.h
/usr/lib/jvm/java-1.12.0-openjdk/include/jvmticmlr.h
/usr/lib/jvm/java-1.12.0-openjdk/include/linux/jawt_md.h
/usr/lib/jvm/java-1.12.0-openjdk/include/linux/jni_md.h
/usr/lib64/libjli12.so

%files lib
%defattr(-,root,root,-)
/usr/lib/jvm/java-1.12.0-openjdk/lib/libattach.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libawt.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libawt_headless.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libawt_xawt.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libdt_socket.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libextnet.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libfontmanager.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libinstrument.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libj2gss.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libj2pcsc.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libj2pkcs11.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjaas.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjava.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjavajpeg.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjawt.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjdwp.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjimage.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjli.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjsig.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libjsound.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/liblcms.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libmanagement.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libmanagement_agent.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libmanagement_ext.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libmlib_image.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libnet.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libnio.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libprefs.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/librmi.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libsaproc.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libsctp.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libsplashscreen.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libsunec.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libunpack.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libverify.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/libzip.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/server/libjsig.so
/usr/lib/jvm/java-1.12.0-openjdk/lib/server/libjvm.so
